a=int(input('enter value of a'))
b=int(input('enter value of b'))
print('addition is',a+b)
print('subtraction is',a-b)
print('divisionis',a/b)
print('multiplication is',a*b)
print('floordivision is',a//b)
print('modulus is',a%b)
print('exponansial is',a**b)
print('equaltoopreator is',a==b)
print('notequalto is',a!=b)